# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class English < Formula
  desc "Learning English with CLI."
  homepage "https://zeliclabs.com"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zelic91/english-binaries/releases/download/v1.0.0/english-binaries_Darwin_x86_64.tar.gz"
      sha256 "711b71e4729e4f4c2c8fd0e61469892b6f142570b75a628b5cd82b9a561872af"

      define_method(:install) do
        bin.install "english"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zelic91/english-binaries/releases/download/v1.0.0/english-binaries_Darwin_arm64.tar.gz"
      sha256 "afee737e841c55fc22c636e3b3437c4dc88fe4be99fa2b69cdad5e5d694a20aa"

      define_method(:install) do
        bin.install "english"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zelic91/english-binaries/releases/download/v1.0.0/english-binaries_Linux_x86_64.tar.gz"
      sha256 "4e073072aecb6a01c54a76ad260234f63ba9072027268ad70fd38c7ac35e9f09"
      define_method(:install) do
        bin.install "english"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zelic91/english-binaries/releases/download/v1.0.0/english-binaries_Linux_arm64.tar.gz"
      sha256 "a4e42f805a8cd57740d31e8106859807c8659081c538a516069cfbf912e0943c"
      define_method(:install) do
        bin.install "english"
      end
    end
  end
end
